<svelte:head>
	<title>Terms of Use — Orchestra Melody & Harmony</title>
	<meta name="description" content="Terms of use for Orchestra Melody & Harmony" />
</svelte:head>

<div class="mx-auto max-w-5xl px-6 py-12">
	<h1 class="mb-8 text-3xl font-bold">Terms of Use</h1>

	<div class="space-y-6 text-zinc-300">
		<section>
			<h2 class="mb-3 text-xl font-semibold">Agreement to Terms</h2>
			<p>
				By using Orchestra Melody & Harmony, you agree to comply with these terms. If you do not
				agree, please do not use this service.
			</p>
		</section>

		<section>
			<h2 class="mb-3 text-xl font-semibold">Disclaimer</h2>
			<p>
				Orchestra Melody & Harmony is provided "as-is" without warranty of any kind. The
				recommendations are generated based on benchmarks and should be verified before making
				production decisions.
			</p>
		</section>

		<section>
			<h2 class="mb-3 text-xl font-semibold">Limitation of Liability</h2>
			<p>
				We are not liable for any damage, loss, or error resulting from the use of this service or
				the recommendations provided.
			</p>
		</section>

		<section>
			<h2 class="mb-3 text-xl font-semibold">Acceptable Use</h2>
			<p>You agree not to:</p>
			<ul class="mt-2 list-inside list-disc space-y-1 text-zinc-400">
				<li>Attempt to abuse the rate limiting system or disrupt the service</li>
				<li>Use the service for any illegal or harmful purpose</li>
				<li>Attempt to reverse-engineer or access underlying systems</li>
			</ul>
		</section>

		<section>
			<h2 class="mb-3 text-xl font-semibold">Intellectual Property</h2>
			<p>
				The recommendations and data generated by this service are provided for your use. Model
				names, benchmarks, and pricing are sourced from OpenRouter and HuggingFace.
			</p>
		</section>

		<section>
			<h2 class="mb-3 text-xl font-semibold">Changes to Terms</h2>
			<p>
				We may update these terms from time to time. The most current version will always be
				available on this page.
			</p>
		</section>

		<section>
			<h2 class="mb-3 text-xl font-semibold">Contact</h2>
			<p>
				For questions about these terms, please contact us at
				<a
					href="https://orchestraproduction.krystalmartinez.com"
					class="underline hover:text-zinc-100"
				>
					Orchestra Production
				</a>.
			</p>
		</section>
	</div>
</div>
